export const GAME_CONFIG = {
    MAX_COINS: 100,
    COIN_POOL_SIZE: 150,
    INITIAL_COINS: 20,
    PUSHER_AMPLITUDE: 1.5,
    PUSHER_FREQUENCY: 0.005,
    COIN_REMOVAL_THRESHOLD_Y: -2,
    COIN_REMOVAL_THRESHOLD_Z: 5,
    COIN_DISTANCE_THRESHOLD: 8,
    COIN_SPEED_THRESHOLD: 0.1,
    GRAVITY: 9.82, // m/s^2
  };